name: local_ticks_api
description: local implementation of the ticks API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  ticks_api:
    path: ../ticks_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0