name: ticks_domain
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.8.1
  meta: ^1.7.0
  uuid: ^4.0.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
